### ISSUE TITLE
Completed module 3a assignments

### ISSUE THREAD

**Issue by hsjakpa** [ds4owd-001/md-03-assignments-hsjakpa#1]
@larnsce @mianzg @sskorik01

**Comment by sskorik01** [comment]
Congratulations for completing the first part of the homework Horace! Just a little remark when you want to filter for several conditions, you have to be careful about the operator, a comma does not count as an "AND" or an "OR" operator. 

For example, to create a subset from penguins that only contains observations for Adelie penguins with a bill length greater than 40 mm, you want penguins that fulfill both conditions so you would use the operator & (AND)

```{r}
penguins |> 
  filter(species == "Adelie" & bill_length_mm > 40)
```

However, to create a subset from penguins that contains penguins that are either gentoos OR have a body mass greater than 4500g, you would use the operator | (OR)

```{r}
penguins |> 
  filter(species == "Gentoo" | body_mass_g > 4500)
```

Also be careful about the smaller equal (<=) versus strictly smaller (<). For example, to create a subset from penguins that contains observations for female Adelie penguins with bill lengths less than 35 mm, you want to use strictly smaller 

```{r}
penguins |> 
  filter(sex == "female", species == "Adelie", bill_length_mm < 35)
```
